on:
    push:
        tags:
            - '*'

jobs:
    build:
        permissions:
            contents: write
        name: Build
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install g++-multilib
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install g++-multilib
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Set up node-gyp
              run: npm i -g node-gyp
            - name: Build native modules
              run: node-gyp rebuild --target=30.0.1 --arch=x64 --dist-url=https://atom.io/download/electron
              working-directory: ./mouseDriver
            - name: Generate build info
              run: node buildinfo.js
            - name: Transpile
              run: npm run transpile
            - name: Build
              run: npx electron-builder --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
